<!Doctype HTML>
<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
        <title>ITMG - Investor Database Relation</title>

        <link rel="stylesheet" href="<?php echo $this->baseUrl('resources/css/ext-all.css')?>" type="text/css" />
        <link rel="stylesheet" href="<?php echo $this->baseUrl('resources/themes/itm/itm.css')?>" />
        <link rel="stylesheet" href="<?php echo $this->baseUrl('resources/themes/itm/ext-layout.css')?>" />
        
        <!-- GC -->
        
        <!-- <x-compile> -->
        <!-- <x-bootstrap> -->
        <script type="text/javascript" src="<?php echo $this->baseUrl('resources/extjs/ext-all.js')?>"></script>
        <!-- </x-bootstrap> -->
        <script type="text/javascript" src="<?php echo $this->baseUrl('app.js')?>"></script>
        <!-- </x-compile> -->
        
    </head>
    <body>
        <?php echo $this->layout()->content . "\n" ?>
    </body>
</html>