<!doctype html>
<html>
<head>
	<meta charset="utf-8">
	<title>ExtJS LABS</title>
	<!-- Start : CSS -->
	<link rel="stylesheet" href="<?php echo $this->baseUrl('resources/css/ext-all.css')?>" type="text/css" />
	<link rel="stylesheet" href="<?php echo $this->baseUrl('resources/css/style.css')?>" type="text/css" />
	<!-- End of : CSS -->
	<!-- Start : JS -->
	<script type="text/javascript" src="<?php echo $this->baseUrl('resources/js/ext-all.js')?>"></script>
	<script type="text/javascript" src="app.js"></script>
	<!-- End of : JS -->
</head>
<body>

	<?php echo $this->layout()->content ?>
	
</body>
</html>
