<!Doctype HTML>
<html>
    <head>
        <meta charset="utf-8">
        <title>ITMG - Investor Database Relation</title>
        <!-- # ExtJS Resources -->
        <link rel="stylesheet" href="<?php echo $this->baseUrl('resources/css/ext-all.css')?>" type="text/css" />
        <script type="text/javascript" src="<?php echo $this->baseUrl('resources/extjs/ext-all.js')?>"></script>
        <!-- # End Of : ExtJS Resources -->
        <link rel="stylesheet" href="<?php echo $this->baseUrl('resources/themes/itm/itm.css')?>" />
        <link rel="stylesheet" href="<?php echo $this->baseUrl('resources/themes/itm/ext-layout.css')?>" />
    </head>
    <body>
        <?php echo $this->layout()->content . "\n" ?>
    </body>
</html>